// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

public interface PVorabpauschaleEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name.abuchen.portfolio.PVorabpauschaleEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string security = 1;</code>
   * @return The security.
   */
  java.lang.String getSecurity();
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string security = 1;</code>
   * @return The bytes for security.
   */
  com.google.protobuf.ByteString
      getSecurityBytes();

  /**
   * <code>int32 year = 2;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string basiszins = 3;</code>
   * @return The basiszins.
   */
  java.lang.String getBasiszins();
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string basiszins = 3;</code>
   * @return The bytes for basiszins.
   */
  com.google.protobuf.ByteString
      getBasiszinsBytes();

  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string teilfreistellungFactor = 4;</code>
   * @return The teilfreistellungFactor.
   */
  java.lang.String getTeilfreistellungFactor();
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string teilfreistellungFactor = 4;</code>
   * @return The bytes for teilfreistellungFactor.
   */
  com.google.protobuf.ByteString
      getTeilfreistellungFactorBytes();

  /**
   * <code>int64 yearStartValue = 5;</code>
   * @return The yearStartValue.
   */
  long getYearStartValue();

  /**
   * <code>int64 distributions = 6;</code>
   * @return The distributions.
   */
  long getDistributions();

  /**
   * <code>int64 cappedBasisertrag = 7;</code>
   * @return The cappedBasisertrag.
   */
  long getCappedBasisertrag();

  /**
   * <code>int64 vorabpauschale = 8;</code>
   * @return The vorabpauschale.
   */
  long getVorabpauschale();

  /**
   * <code>int64 taxable = 9;</code>
   * @return The taxable.
   */
  long getTaxable();

  /**
   * <pre>
   * shared currency for all money fields
   * </pre>
   *
   * <code>string currencyCode = 10;</code>
   * @return The currencyCode.
   */
  java.lang.String getCurrencyCode();
  /**
   * <pre>
   * shared currency for all money fields
   * </pre>
   *
   * <code>string currencyCode = 10;</code>
   * @return The bytes for currencyCode.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   * @return Whether the finalizedAt field is set.
   */
  boolean hasFinalizedAt();
  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   * @return The finalizedAt.
   */
  com.google.protobuf.Timestamp getFinalizedAt();
  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getFinalizedAtOrBuilder();
}
