// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package name.abuchen.portfolio.model.proto.v1;

/**
 * Protobuf type {@code name.abuchen.portfolio.PVorabpauschaleEntry}
 */
public final class PVorabpauschaleEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:name.abuchen.portfolio.PVorabpauschaleEntry)
    PVorabpauschaleEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PVorabpauschaleEntry.newBuilder() to construct.
  private PVorabpauschaleEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PVorabpauschaleEntry() {
    security_ = "";
    basiszins_ = "";
    teilfreistellungFactor_ = "";
    currencyCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PVorabpauschaleEntry();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PVorabpauschaleEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PVorabpauschaleEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.class, name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.Builder.class);
  }

  public static final int SECURITY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object security_ = "";
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string security = 1;</code>
   * @return The security.
   */
  @java.lang.Override
  public java.lang.String getSecurity() {
    java.lang.Object ref = security_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      security_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * uuid
   * </pre>
   *
   * <code>string security = 1;</code>
   * @return The bytes for security.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecurityBytes() {
    java.lang.Object ref = security_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      security_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEAR_FIELD_NUMBER = 2;
  private int year_ = 0;
  /**
   * <code>int32 year = 2;</code>
   * @return The year.
   */
  @java.lang.Override
  public int getYear() {
    return year_;
  }

  public static final int BASISZINS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object basiszins_ = "";
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string basiszins = 3;</code>
   * @return The basiszins.
   */
  @java.lang.Override
  public java.lang.String getBasiszins() {
    java.lang.Object ref = basiszins_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      basiszins_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string basiszins = 3;</code>
   * @return The bytes for basiszins.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBasiszinsBytes() {
    java.lang.Object ref = basiszins_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      basiszins_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEILFREISTELLUNGFACTOR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object teilfreistellungFactor_ = "";
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string teilfreistellungFactor = 4;</code>
   * @return The teilfreistellungFactor.
   */
  @java.lang.Override
  public java.lang.String getTeilfreistellungFactor() {
    java.lang.Object ref = teilfreistellungFactor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      teilfreistellungFactor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * BigDecimal as plain string
   * </pre>
   *
   * <code>string teilfreistellungFactor = 4;</code>
   * @return The bytes for teilfreistellungFactor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTeilfreistellungFactorBytes() {
    java.lang.Object ref = teilfreistellungFactor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      teilfreistellungFactor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEARSTARTVALUE_FIELD_NUMBER = 5;
  private long yearStartValue_ = 0L;
  /**
   * <code>int64 yearStartValue = 5;</code>
   * @return The yearStartValue.
   */
  @java.lang.Override
  public long getYearStartValue() {
    return yearStartValue_;
  }

  public static final int DISTRIBUTIONS_FIELD_NUMBER = 6;
  private long distributions_ = 0L;
  /**
   * <code>int64 distributions = 6;</code>
   * @return The distributions.
   */
  @java.lang.Override
  public long getDistributions() {
    return distributions_;
  }

  public static final int CAPPEDBASISERTRAG_FIELD_NUMBER = 7;
  private long cappedBasisertrag_ = 0L;
  /**
   * <code>int64 cappedBasisertrag = 7;</code>
   * @return The cappedBasisertrag.
   */
  @java.lang.Override
  public long getCappedBasisertrag() {
    return cappedBasisertrag_;
  }

  public static final int VORABPAUSCHALE_FIELD_NUMBER = 8;
  private long vorabpauschale_ = 0L;
  /**
   * <code>int64 vorabpauschale = 8;</code>
   * @return The vorabpauschale.
   */
  @java.lang.Override
  public long getVorabpauschale() {
    return vorabpauschale_;
  }

  public static final int TAXABLE_FIELD_NUMBER = 9;
  private long taxable_ = 0L;
  /**
   * <code>int64 taxable = 9;</code>
   * @return The taxable.
   */
  @java.lang.Override
  public long getTaxable() {
    return taxable_;
  }

  public static final int CURRENCYCODE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currencyCode_ = "";
  /**
   * <pre>
   * shared currency for all money fields
   * </pre>
   *
   * <code>string currencyCode = 10;</code>
   * @return The currencyCode.
   */
  @java.lang.Override
  public java.lang.String getCurrencyCode() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currencyCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * shared currency for all money fields
   * </pre>
   *
   * <code>string currencyCode = 10;</code>
   * @return The bytes for currencyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyCodeBytes() {
    java.lang.Object ref = currencyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currencyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FINALIZEDAT_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp finalizedAt_;
  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   * @return Whether the finalizedAt field is set.
   */
  @java.lang.Override
  public boolean hasFinalizedAt() {
    return finalizedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   * @return The finalizedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getFinalizedAt() {
    return finalizedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : finalizedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getFinalizedAtOrBuilder() {
    return finalizedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : finalizedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(security_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, security_);
    }
    if (year_ != 0) {
      output.writeInt32(2, year_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basiszins_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, basiszins_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teilfreistellungFactor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, teilfreistellungFactor_);
    }
    if (yearStartValue_ != 0L) {
      output.writeInt64(5, yearStartValue_);
    }
    if (distributions_ != 0L) {
      output.writeInt64(6, distributions_);
    }
    if (cappedBasisertrag_ != 0L) {
      output.writeInt64(7, cappedBasisertrag_);
    }
    if (vorabpauschale_ != 0L) {
      output.writeInt64(8, vorabpauschale_);
    }
    if (taxable_ != 0L) {
      output.writeInt64(9, taxable_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, currencyCode_);
    }
    if (finalizedAt_ != null) {
      output.writeMessage(11, getFinalizedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(security_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, security_);
    }
    if (year_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, year_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basiszins_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, basiszins_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teilfreistellungFactor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, teilfreistellungFactor_);
    }
    if (yearStartValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, yearStartValue_);
    }
    if (distributions_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, distributions_);
    }
    if (cappedBasisertrag_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, cappedBasisertrag_);
    }
    if (vorabpauschale_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, vorabpauschale_);
    }
    if (taxable_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, taxable_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currencyCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, currencyCode_);
    }
    if (finalizedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getFinalizedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry)) {
      return super.equals(obj);
    }
    name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry other = (name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry) obj;

    if (!getSecurity()
        .equals(other.getSecurity())) return false;
    if (getYear()
        != other.getYear()) return false;
    if (!getBasiszins()
        .equals(other.getBasiszins())) return false;
    if (!getTeilfreistellungFactor()
        .equals(other.getTeilfreistellungFactor())) return false;
    if (getYearStartValue()
        != other.getYearStartValue()) return false;
    if (getDistributions()
        != other.getDistributions()) return false;
    if (getCappedBasisertrag()
        != other.getCappedBasisertrag()) return false;
    if (getVorabpauschale()
        != other.getVorabpauschale()) return false;
    if (getTaxable()
        != other.getTaxable()) return false;
    if (!getCurrencyCode()
        .equals(other.getCurrencyCode())) return false;
    if (hasFinalizedAt() != other.hasFinalizedAt()) return false;
    if (hasFinalizedAt()) {
      if (!getFinalizedAt()
          .equals(other.getFinalizedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SECURITY_FIELD_NUMBER;
    hash = (53 * hash) + getSecurity().hashCode();
    hash = (37 * hash) + YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getYear();
    hash = (37 * hash) + BASISZINS_FIELD_NUMBER;
    hash = (53 * hash) + getBasiszins().hashCode();
    hash = (37 * hash) + TEILFREISTELLUNGFACTOR_FIELD_NUMBER;
    hash = (53 * hash) + getTeilfreistellungFactor().hashCode();
    hash = (37 * hash) + YEARSTARTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getYearStartValue());
    hash = (37 * hash) + DISTRIBUTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDistributions());
    hash = (37 * hash) + CAPPEDBASISERTRAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCappedBasisertrag());
    hash = (37 * hash) + VORABPAUSCHALE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVorabpauschale());
    hash = (37 * hash) + TAXABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTaxable());
    hash = (37 * hash) + CURRENCYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrencyCode().hashCode();
    if (hasFinalizedAt()) {
      hash = (37 * hash) + FINALIZEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getFinalizedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code name.abuchen.portfolio.PVorabpauschaleEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:name.abuchen.portfolio.PVorabpauschaleEntry)
      name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PVorabpauschaleEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PVorabpauschaleEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.class, name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.Builder.class);
    }

    // Construct using name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      security_ = "";
      year_ = 0;
      basiszins_ = "";
      teilfreistellungFactor_ = "";
      yearStartValue_ = 0L;
      distributions_ = 0L;
      cappedBasisertrag_ = 0L;
      vorabpauschale_ = 0L;
      taxable_ = 0L;
      currencyCode_ = "";
      finalizedAt_ = null;
      if (finalizedAtBuilder_ != null) {
        finalizedAtBuilder_.dispose();
        finalizedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return name.abuchen.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PVorabpauschaleEntry_descriptor;
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry getDefaultInstanceForType() {
      return name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.getDefaultInstance();
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry build() {
      name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry buildPartial() {
      name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry result = new name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.security_ = security_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.year_ = year_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.basiszins_ = basiszins_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.teilfreistellungFactor_ = teilfreistellungFactor_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.yearStartValue_ = yearStartValue_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.distributions_ = distributions_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.cappedBasisertrag_ = cappedBasisertrag_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.vorabpauschale_ = vorabpauschale_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.taxable_ = taxable_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.currencyCode_ = currencyCode_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.finalizedAt_ = finalizedAtBuilder_ == null
            ? finalizedAt_
            : finalizedAtBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry) {
        return mergeFrom((name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry other) {
      if (other == name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry.getDefaultInstance()) return this;
      if (!other.getSecurity().isEmpty()) {
        security_ = other.security_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getYear() != 0) {
        setYear(other.getYear());
      }
      if (!other.getBasiszins().isEmpty()) {
        basiszins_ = other.basiszins_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTeilfreistellungFactor().isEmpty()) {
        teilfreistellungFactor_ = other.teilfreistellungFactor_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getYearStartValue() != 0L) {
        setYearStartValue(other.getYearStartValue());
      }
      if (other.getDistributions() != 0L) {
        setDistributions(other.getDistributions());
      }
      if (other.getCappedBasisertrag() != 0L) {
        setCappedBasisertrag(other.getCappedBasisertrag());
      }
      if (other.getVorabpauschale() != 0L) {
        setVorabpauschale(other.getVorabpauschale());
      }
      if (other.getTaxable() != 0L) {
        setTaxable(other.getTaxable());
      }
      if (!other.getCurrencyCode().isEmpty()) {
        currencyCode_ = other.currencyCode_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.hasFinalizedAt()) {
        mergeFinalizedAt(other.getFinalizedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              security_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              year_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              basiszins_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              teilfreistellungFactor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              yearStartValue_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              distributions_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              cappedBasisertrag_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              vorabpauschale_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              taxable_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              currencyCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getFinalizedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object security_ = "";
    /**
     * <pre>
     * uuid
     * </pre>
     *
     * <code>string security = 1;</code>
     * @return The security.
     */
    public java.lang.String getSecurity() {
      java.lang.Object ref = security_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        security_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * uuid
     * </pre>
     *
     * <code>string security = 1;</code>
     * @return The bytes for security.
     */
    public com.google.protobuf.ByteString
        getSecurityBytes() {
      java.lang.Object ref = security_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        security_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * uuid
     * </pre>
     *
     * <code>string security = 1;</code>
     * @param value The security to set.
     * @return This builder for chaining.
     */
    public Builder setSecurity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      security_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uuid
     * </pre>
     *
     * <code>string security = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecurity() {
      security_ = getDefaultInstance().getSecurity();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * uuid
     * </pre>
     *
     * <code>string security = 1;</code>
     * @param value The bytes for security to set.
     * @return This builder for chaining.
     */
    public Builder setSecurityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      security_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>int32 year = 2;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }
    /**
     * <code>int32 year = 2;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(int value) {

      year_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      bitField0_ = (bitField0_ & ~0x00000002);
      year_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object basiszins_ = "";
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string basiszins = 3;</code>
     * @return The basiszins.
     */
    public java.lang.String getBasiszins() {
      java.lang.Object ref = basiszins_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basiszins_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string basiszins = 3;</code>
     * @return The bytes for basiszins.
     */
    public com.google.protobuf.ByteString
        getBasiszinsBytes() {
      java.lang.Object ref = basiszins_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basiszins_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string basiszins = 3;</code>
     * @param value The basiszins to set.
     * @return This builder for chaining.
     */
    public Builder setBasiszins(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      basiszins_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string basiszins = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBasiszins() {
      basiszins_ = getDefaultInstance().getBasiszins();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string basiszins = 3;</code>
     * @param value The bytes for basiszins to set.
     * @return This builder for chaining.
     */
    public Builder setBasiszinsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      basiszins_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object teilfreistellungFactor_ = "";
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string teilfreistellungFactor = 4;</code>
     * @return The teilfreistellungFactor.
     */
    public java.lang.String getTeilfreistellungFactor() {
      java.lang.Object ref = teilfreistellungFactor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teilfreistellungFactor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string teilfreistellungFactor = 4;</code>
     * @return The bytes for teilfreistellungFactor.
     */
    public com.google.protobuf.ByteString
        getTeilfreistellungFactorBytes() {
      java.lang.Object ref = teilfreistellungFactor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teilfreistellungFactor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string teilfreistellungFactor = 4;</code>
     * @param value The teilfreistellungFactor to set.
     * @return This builder for chaining.
     */
    public Builder setTeilfreistellungFactor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      teilfreistellungFactor_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string teilfreistellungFactor = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeilfreistellungFactor() {
      teilfreistellungFactor_ = getDefaultInstance().getTeilfreistellungFactor();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * BigDecimal as plain string
     * </pre>
     *
     * <code>string teilfreistellungFactor = 4;</code>
     * @param value The bytes for teilfreistellungFactor to set.
     * @return This builder for chaining.
     */
    public Builder setTeilfreistellungFactorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      teilfreistellungFactor_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long yearStartValue_ ;
    /**
     * <code>int64 yearStartValue = 5;</code>
     * @return The yearStartValue.
     */
    @java.lang.Override
    public long getYearStartValue() {
      return yearStartValue_;
    }
    /**
     * <code>int64 yearStartValue = 5;</code>
     * @param value The yearStartValue to set.
     * @return This builder for chaining.
     */
    public Builder setYearStartValue(long value) {

      yearStartValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 yearStartValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearYearStartValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      yearStartValue_ = 0L;
      onChanged();
      return this;
    }

    private long distributions_ ;
    /**
     * <code>int64 distributions = 6;</code>
     * @return The distributions.
     */
    @java.lang.Override
    public long getDistributions() {
      return distributions_;
    }
    /**
     * <code>int64 distributions = 6;</code>
     * @param value The distributions to set.
     * @return This builder for chaining.
     */
    public Builder setDistributions(long value) {

      distributions_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 distributions = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistributions() {
      bitField0_ = (bitField0_ & ~0x00000020);
      distributions_ = 0L;
      onChanged();
      return this;
    }

    private long cappedBasisertrag_ ;
    /**
     * <code>int64 cappedBasisertrag = 7;</code>
     * @return The cappedBasisertrag.
     */
    @java.lang.Override
    public long getCappedBasisertrag() {
      return cappedBasisertrag_;
    }
    /**
     * <code>int64 cappedBasisertrag = 7;</code>
     * @param value The cappedBasisertrag to set.
     * @return This builder for chaining.
     */
    public Builder setCappedBasisertrag(long value) {

      cappedBasisertrag_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cappedBasisertrag = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCappedBasisertrag() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cappedBasisertrag_ = 0L;
      onChanged();
      return this;
    }

    private long vorabpauschale_ ;
    /**
     * <code>int64 vorabpauschale = 8;</code>
     * @return The vorabpauschale.
     */
    @java.lang.Override
    public long getVorabpauschale() {
      return vorabpauschale_;
    }
    /**
     * <code>int64 vorabpauschale = 8;</code>
     * @param value The vorabpauschale to set.
     * @return This builder for chaining.
     */
    public Builder setVorabpauschale(long value) {

      vorabpauschale_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 vorabpauschale = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVorabpauschale() {
      bitField0_ = (bitField0_ & ~0x00000080);
      vorabpauschale_ = 0L;
      onChanged();
      return this;
    }

    private long taxable_ ;
    /**
     * <code>int64 taxable = 9;</code>
     * @return The taxable.
     */
    @java.lang.Override
    public long getTaxable() {
      return taxable_;
    }
    /**
     * <code>int64 taxable = 9;</code>
     * @param value The taxable to set.
     * @return This builder for chaining.
     */
    public Builder setTaxable(long value) {

      taxable_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 taxable = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaxable() {
      bitField0_ = (bitField0_ & ~0x00000100);
      taxable_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object currencyCode_ = "";
    /**
     * <pre>
     * shared currency for all money fields
     * </pre>
     *
     * <code>string currencyCode = 10;</code>
     * @return The currencyCode.
     */
    public java.lang.String getCurrencyCode() {
      java.lang.Object ref = currencyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currencyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * shared currency for all money fields
     * </pre>
     *
     * <code>string currencyCode = 10;</code>
     * @return The bytes for currencyCode.
     */
    public com.google.protobuf.ByteString
        getCurrencyCodeBytes() {
      java.lang.Object ref = currencyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currencyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * shared currency for all money fields
     * </pre>
     *
     * <code>string currencyCode = 10;</code>
     * @param value The currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currencyCode_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * shared currency for all money fields
     * </pre>
     *
     * <code>string currencyCode = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrencyCode() {
      currencyCode_ = getDefaultInstance().getCurrencyCode();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * shared currency for all money fields
     * </pre>
     *
     * <code>string currencyCode = 10;</code>
     * @param value The bytes for currencyCode to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currencyCode_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp finalizedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> finalizedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     * @return Whether the finalizedAt field is set.
     */
    public boolean hasFinalizedAt() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     * @return The finalizedAt.
     */
    public com.google.protobuf.Timestamp getFinalizedAt() {
      if (finalizedAtBuilder_ == null) {
        return finalizedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : finalizedAt_;
      } else {
        return finalizedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public Builder setFinalizedAt(com.google.protobuf.Timestamp value) {
      if (finalizedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        finalizedAt_ = value;
      } else {
        finalizedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public Builder setFinalizedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (finalizedAtBuilder_ == null) {
        finalizedAt_ = builderForValue.build();
      } else {
        finalizedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public Builder mergeFinalizedAt(com.google.protobuf.Timestamp value) {
      if (finalizedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          finalizedAt_ != null &&
          finalizedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getFinalizedAtBuilder().mergeFrom(value);
        } else {
          finalizedAt_ = value;
        }
      } else {
        finalizedAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public Builder clearFinalizedAt() {
      bitField0_ = (bitField0_ & ~0x00000400);
      finalizedAt_ = null;
      if (finalizedAtBuilder_ != null) {
        finalizedAtBuilder_.dispose();
        finalizedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public com.google.protobuf.Timestamp.Builder getFinalizedAtBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getFinalizedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFinalizedAtOrBuilder() {
      if (finalizedAtBuilder_ != null) {
        return finalizedAtBuilder_.getMessageOrBuilder();
      } else {
        return finalizedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : finalizedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp finalizedAt = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getFinalizedAtFieldBuilder() {
      if (finalizedAtBuilder_ == null) {
        finalizedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getFinalizedAt(),
                getParentForChildren(),
                isClean());
        finalizedAt_ = null;
      }
      return finalizedAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:name.abuchen.portfolio.PVorabpauschaleEntry)
  }

  // @@protoc_insertion_point(class_scope:name.abuchen.portfolio.PVorabpauschaleEntry)
  private static final name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry();
  }

  public static name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PVorabpauschaleEntry>
      PARSER = new com.google.protobuf.AbstractParser<PVorabpauschaleEntry>() {
    @java.lang.Override
    public PVorabpauschaleEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PVorabpauschaleEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PVorabpauschaleEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public name.abuchen.portfolio.model.proto.v1.PVorabpauschaleEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

